# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ 
      "xhci_pci" 
      "nvme" 
      "usb_storage" 
      "sd_mod"
      "hid"
      "i2c_core"
      "i2c_hid"
      "i2c_designware_core"
      "i2c_designware_platform"
    ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ 
    "kvm-intel"
    "hid"
    "i2c_core"
    "i2c_hid"
    "i2c_designware_core"
    "i2c_designware_platform"
  ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [
    "elan_i2c"
  ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7a909451-0e43-4445-89d1-3eb56e50f61d";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/4489c013-891e-4fd0-9497-e7728b020736";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EAF6-52FA";
      fsType = "vfat";
    };

  #fileSystems."/private" =
  #  { device = "/dev/disk/by-uuid/5134eef7-a621-4fec-8210-c7873a65d1f7";
  #    fsType = "ext4";
  #  };

  #boot.initrd.luks.devices."private".device = "/dev/disk/by-uuid/c86cd89d-7261-4cbf-bb8d-0f1e1cdc35fe";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/247305b7-1a6f-4dac-994a-dc634d25ad77"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wls6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.support32Bit = true;
  hardware.bluetooth.enable = true;

}
